server:
    port: ${PORT:8080}
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        gateway:
            access: read_only

spring:
    cloud:
        gateway:
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowed-origins:
                            - "*"
                        allowed-methods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
                            - OPTIONS
                            - PATCH
                        allowed-headers:
                            - "*"
#                        allow-credentials: true
            # Global filters không còn sử dụng GlobalAuthenticationFilter
            default-filters: []
            # Route configurations
#            routes:
#                - id: user-service
#                  uri: lb://USER-SERVICE
#                  predicates:
#                      - Path=/api/v1/users/**, /api/v1/auth/**
#                  filters:
#                      - StripPrefix=2

    application:
        name: API-GATEWAY

# JWT Configuration (should match with user service)
application:
    security:
        jwt:
            # Đảm bảo cùng secret key với User Service
            secret-key: ${JWT_SECRET_KEY}
            expiration: ${JWT_EXPIRATION:86400000} # 1 day in milliseconds

eureka:
    client:
        service-url:
            defaultZone: ${DEFAULT_REGIS:http://localhost:8761/eureka/}

logging:
    level:
        org.springframework.cloud.gateway: DEBUG
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG
        com.se.apigateway: DEBUG
