spring:
    application:
        name: ACCOUNTANT

    datasource:
        url: ${URL:jdbc:mysql://localhost:3306/hms_db}
        username: ${USERNAME:root}
        password: ${PASSWORD:root}
        driverClassName: "com.mysql.cj.jdbc.Driver"
    jpa:
        hibernate:
          ddl-auto: update
        open-in-view: false
